# Generated by Django 5.2 on 2025-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=16)),
                ('context', models.TextField(max_length=8192)),
                ('content', models.TextField(max_length=20480)),
            ],
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs'),
        ),
    ]
