# Generated by Django 5.1.11 on 2025-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chat_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("import_id", models.BigIntegerField()),
                ("project", models.IntegerField()),
                ("comprehensiveness", models.IntegerField()),
                ("completeness", models.IntegerField()),
                ("task", models.IntegerField()),
                ("was_cancelled", models.BooleanField()),
            ],
        ),
    ]
