name: Build and Push Images

on: 
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: CHeckout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./custom_gpt
          file: ./custom_gpt/Dockerfile
          push: true
          no-cache: true
          tags: |
              registry.zaidyusuf.com/t2grag-api:latest
              registry.zaidyusuf.com/t2grag-api:${{ github.sha }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          no-cache: true
          tags: |
              registry.zaidyusuf.com/t2grag-web:latest
              registry.zaidyusuf.com/t2grag-web:${{ github.sha }}
